# Generated by Django 5.0.3 on 2024-03-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="amount",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="container",
            name="navg",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="container",
            name="ncbm",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
