# Generated by Django 5.0.3 on 2024-03-14 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_logsinfo_alter_container_navg_alter_container_ncbm"),
    ]

    operations = [
        migrations.AddField(
            model_name="logsinfo",
            name="container",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.container",
            ),
            preserve_default=False,
        ),
    ]
