# Generated by Django 5.0.3 on 2024-04-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_container_navg_alter_container_ncbm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="container_number",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
