# Generated by Django 5.0.3 on 2024-04-03 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_container_container_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finishedlog',
            old_name='height',
            new_name='thickness',
        ),
    ]
