# Generated by Django 5.0.3 on 2024-04-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_log_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedlog',
            name='reference_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='log',
            name='reference_id',
            field=models.IntegerField(default=0),
        ),
    ]
