# Generated by Django 5.0.3 on 2024-04-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_rename_cft_cbm_log_cbm_log_cft"),
    ]

    operations = [
        migrations.AddField(
            model_name="finishedlog",
            name="cft",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=20, null=True
            ),
        ),
    ]
