# Generated by Django 5.0.3 on 2024-04-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_finishedlog_cft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishedlog',
            name='cft',
        ),
    ]
