# Generated by Django 5.0.3 on 2024-04-05 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_container_a_navg_container_number_pieces_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="container",
            name="a_navg",
        ),
        migrations.RemoveField(
            model_name="container",
            name="number_pieces",
        ),
        migrations.RemoveField(
            model_name="container",
            name="total_cbm",
        ),
    ]
