# Generated by Django 5.0.3 on 2024-04-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_alter_finishedlog_cft_alter_log_cbm_alter_log_cft_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="a_navg",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="navg",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="container",
            name="ncbm",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="container",
            name="total_cbm",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0, max_digits=20, null=True
            ),
        ),
    ]
