# Generated by Django 5.0.3 on 2024-04-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_alter_container_a_navg_alter_container_navg_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finishedlog",
            name="length",
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="finishedlog",
            name="thickness",
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="finishedlog",
            name="width",
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
