# Generated by Django 5.0.3 on 2024-04-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_alter_finishedlog_length_alter_finishedlog_thickness_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="amount",
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name="container",
            name="navg",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="container",
            name="ncbm",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
