# Generated by Django 5.0.3 on 2024-04-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_alter_container_amount_alter_container_navg_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="amount",
            field=models.CharField(default=0, max_length=20),
        ),
    ]
