# Generated by Django 5.0.3 on 2024-04-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_alter_container_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="sort_axis_cbm",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="sort_axis_navg",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="sort_axis_pieces",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
