# Generated by Django 5.0.3 on 2024-04-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_container_sort_axis_cbm_container_sort_axis_navg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="status",
            field=models.CharField(
                choices=[("lock", "Locked"), ("draft", "Draft")],
                default="draft",
                max_length=5,
            ),
        ),
    ]
