# Generated by Django 5.0.3 on 2024-04-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_remove_container_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="status",
            field=models.CharField(
                choices=[("lock", "Locked"), ("draft", "Draft")],
                default="draft",
                max_length=5,
            ),
        ),
    ]
