# Generated by Django 5.0.3 on 2024-04-25 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_container_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaleOrderline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("width", models.CharField(max_length=20)),
                ("thickness", models.CharField(max_length=20)),
                ("length", models.CharField(max_length=20)),
                ("quantity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SaleOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sale_date", models.DateField(auto_now_add=True)),
                (
                    "orderline_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.saleorderline",
                    ),
                ),
            ],
        ),
    ]
