# Generated by Django 5.0.3 on 2024-04-26 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_saleorderline_saleorder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saleorderline",
            name="length",
        ),
    ]
