# Generated by Django 5.0.3 on 2024-04-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_remove_saleorderline_length"),
    ]

    operations = [
        migrations.RenameField(
            model_name="saleorder",
            old_name="orderline_id",
            new_name="orderline",
        ),
    ]
