# Generated by Django 5.0.3 on 2024-04-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_rename_orderline_id_saleorder_orderline"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleorderline",
            name="length",
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
